### ISSUE TITLE
Play next video in playlist automatically

### ISSUE THREAD

**Issue by durazell** [lejenome/youtube-html5-player#9]
This addon is great for watching normal youtube videos but I noticed videos don't switch to next one after finishing playing in "watch later" playlist. Add support for that please, so i can just open a playlist and put it to background tab. Something like code below can do it.

```
function playNextOnFinish() {
	if (document.getElementsByClassName("playlist-header").length > 0) {
		document.getElementById("video_player").onended = function(e) {
			var cur = document.getElementById("playlist-current-index").innerHTML;
			var len = document.getElementById("playlist-length").innerHTML;

			if (isNaN(parseInt(cur)) === true || isNaN(parseInt(len)) === true) {
				alert("Cannot find location in playlist, autoplay failed");
				return;
			}

			if ( parseInt(cur) < parseInt(len) ) {
				window.location.href = document.getElementsByClassName("yt-uix-scroller-scroll-unit")[cur].getElementsByTagName("a")[0].href;
			}
		};
	}
}
```

**Comment by lejenome** [comment]
Thx you very much.

fixed by this commit  https://github.com/lejenome/html5-video-everywhere/commit/27ddd752cb37a8d5fc06fc151dc6f0c0e0b400e2 on a new generic extension I'm working on. and syned the changes back to this extension.
